//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace mz.erp.commontypes.data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class tfi_CotizacionesMonedasDataset : DataSet {
        
        private tfi_CotizacionesMonedasDataTable tabletfi_CotizacionesMonedas;
        
        public tfi_CotizacionesMonedasDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected tfi_CotizacionesMonedasDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tfi_CotizacionesMonedas"] != null)) {
                    this.Tables.Add(new tfi_CotizacionesMonedasDataTable(ds.Tables["tfi_CotizacionesMonedas"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tfi_CotizacionesMonedasDataTable tfi_CotizacionesMonedas {
            get {
                return this.tabletfi_CotizacionesMonedas;
            }
        }
        
        public override DataSet Clone() {
            tfi_CotizacionesMonedasDataset cln = ((tfi_CotizacionesMonedasDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tfi_CotizacionesMonedas"] != null)) {
                this.Tables.Add(new tfi_CotizacionesMonedasDataTable(ds.Tables["tfi_CotizacionesMonedas"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletfi_CotizacionesMonedas = ((tfi_CotizacionesMonedasDataTable)(this.Tables["tfi_CotizacionesMonedas"]));
            if ((this.tabletfi_CotizacionesMonedas != null)) {
                this.tabletfi_CotizacionesMonedas.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "tfi_CotizacionesMonedasDataset";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/tfi_CotizacionesMonedas.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletfi_CotizacionesMonedas = new tfi_CotizacionesMonedasDataTable();
            this.Tables.Add(this.tabletfi_CotizacionesMonedas);
        }
        
        private bool ShouldSerializetfi_CotizacionesMonedas() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tfi_CotizacionesMonedasRowChangeEventHandler(object sender, tfi_CotizacionesMonedasRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_CotizacionesMonedasDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnIdCotizacionMoneda;
            
            private DataColumn columnIdMonedaOrigen;
            
            private DataColumn columnIdMonedaDestino;
            
            private DataColumn columnFechaDeCambioInicio;
            
            private DataColumn columnFechaDeCambioFin;
            
            private DataColumn columnIdFuenteDeCambio;
            
            private DataColumn columnValor;
            
            private DataColumn columnFechaCreacion;
            
            private DataColumn columnIdConexionCreacion;
            
            private DataColumn columnUltimaModificacion;
            
            private DataColumn columnIdConexionUltimaModificacion;
            
            private DataColumn columnIdReservado;
            
            private DataColumn columnRowId;
            
            private DataColumn columnIdEmpresa;
            
            private DataColumn columnIdSucursal;
            
            internal tfi_CotizacionesMonedasDataTable() : 
                    base("tfi_CotizacionesMonedas") {
                this.InitClass();
            }
            
            internal tfi_CotizacionesMonedasDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdCotizacionMonedaColumn {
                get {
                    return this.columnIdCotizacionMoneda;
                }
            }
            
            internal DataColumn IdMonedaOrigenColumn {
                get {
                    return this.columnIdMonedaOrigen;
                }
            }
            
            internal DataColumn IdMonedaDestinoColumn {
                get {
                    return this.columnIdMonedaDestino;
                }
            }
            
            internal DataColumn FechaDeCambioInicioColumn {
                get {
                    return this.columnFechaDeCambioInicio;
                }
            }
            
            internal DataColumn FechaDeCambioFinColumn {
                get {
                    return this.columnFechaDeCambioFin;
                }
            }
            
            internal DataColumn IdFuenteDeCambioColumn {
                get {
                    return this.columnIdFuenteDeCambio;
                }
            }
            
            internal DataColumn ValorColumn {
                get {
                    return this.columnValor;
                }
            }
            
            internal DataColumn FechaCreacionColumn {
                get {
                    return this.columnFechaCreacion;
                }
            }
            
            internal DataColumn IdConexionCreacionColumn {
                get {
                    return this.columnIdConexionCreacion;
                }
            }
            
            internal DataColumn UltimaModificacionColumn {
                get {
                    return this.columnUltimaModificacion;
                }
            }
            
            internal DataColumn IdConexionUltimaModificacionColumn {
                get {
                    return this.columnIdConexionUltimaModificacion;
                }
            }
            
            internal DataColumn IdReservadoColumn {
                get {
                    return this.columnIdReservado;
                }
            }
            
            internal DataColumn RowIdColumn {
                get {
                    return this.columnRowId;
                }
            }
            
            internal DataColumn IdEmpresaColumn {
                get {
                    return this.columnIdEmpresa;
                }
            }
            
            internal DataColumn IdSucursalColumn {
                get {
                    return this.columnIdSucursal;
                }
            }
            
            public tfi_CotizacionesMonedasRow this[int index] {
                get {
                    return ((tfi_CotizacionesMonedasRow)(this.Rows[index]));
                }
            }
            
            public event tfi_CotizacionesMonedasRowChangeEventHandler tfi_CotizacionesMonedasRowChanged;
            
            public event tfi_CotizacionesMonedasRowChangeEventHandler tfi_CotizacionesMonedasRowChanging;
            
            public event tfi_CotizacionesMonedasRowChangeEventHandler tfi_CotizacionesMonedasRowDeleted;
            
            public event tfi_CotizacionesMonedasRowChangeEventHandler tfi_CotizacionesMonedasRowDeleting;
            
            public void Addtfi_CotizacionesMonedasRow(tfi_CotizacionesMonedasRow row) {
                this.Rows.Add(row);
            }
            
            public tfi_CotizacionesMonedasRow Addtfi_CotizacionesMonedasRow(string IdCotizacionMoneda, string IdMonedaOrigen, string IdMonedaDestino, System.DateTime FechaDeCambioInicio, System.DateTime FechaDeCambioFin, string IdFuenteDeCambio, System.Decimal Valor, System.DateTime FechaCreacion, long IdConexionCreacion, System.Byte[] UltimaModificacion, long IdConexionUltimaModificacion, long IdReservado, System.Guid RowId, long IdEmpresa, long IdSucursal) {
                tfi_CotizacionesMonedasRow rowtfi_CotizacionesMonedasRow = ((tfi_CotizacionesMonedasRow)(this.NewRow()));
                rowtfi_CotizacionesMonedasRow.ItemArray = new object[] {
                        IdCotizacionMoneda,
                        IdMonedaOrigen,
                        IdMonedaDestino,
                        FechaDeCambioInicio,
                        FechaDeCambioFin,
                        IdFuenteDeCambio,
                        Valor,
                        FechaCreacion,
                        IdConexionCreacion,
                        UltimaModificacion,
                        IdConexionUltimaModificacion,
                        IdReservado,
                        RowId,
                        IdEmpresa,
                        IdSucursal};
                this.Rows.Add(rowtfi_CotizacionesMonedasRow);
                return rowtfi_CotizacionesMonedasRow;
            }
            
            public tfi_CotizacionesMonedasRow FindByIdCotizacionMoneda(string IdCotizacionMoneda) {
                return ((tfi_CotizacionesMonedasRow)(this.Rows.Find(new object[] {
                            IdCotizacionMoneda})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tfi_CotizacionesMonedasDataTable cln = ((tfi_CotizacionesMonedasDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tfi_CotizacionesMonedasDataTable();
            }
            
            internal void InitVars() {
                this.columnIdCotizacionMoneda = this.Columns["IdCotizacionMoneda"];
                this.columnIdMonedaOrigen = this.Columns["IdMonedaOrigen"];
                this.columnIdMonedaDestino = this.Columns["IdMonedaDestino"];
                this.columnFechaDeCambioInicio = this.Columns["FechaDeCambioInicio"];
                this.columnFechaDeCambioFin = this.Columns["FechaDeCambioFin"];
                this.columnIdFuenteDeCambio = this.Columns["IdFuenteDeCambio"];
                this.columnValor = this.Columns["Valor"];
                this.columnFechaCreacion = this.Columns["FechaCreacion"];
                this.columnIdConexionCreacion = this.Columns["IdConexionCreacion"];
                this.columnUltimaModificacion = this.Columns["UltimaModificacion"];
                this.columnIdConexionUltimaModificacion = this.Columns["IdConexionUltimaModificacion"];
                this.columnIdReservado = this.Columns["IdReservado"];
                this.columnRowId = this.Columns["RowId"];
                this.columnIdEmpresa = this.Columns["IdEmpresa"];
                this.columnIdSucursal = this.Columns["IdSucursal"];
            }
            
            private void InitClass() {
                this.columnIdCotizacionMoneda = new DataColumn("IdCotizacionMoneda", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdCotizacionMoneda);
                this.columnIdMonedaOrigen = new DataColumn("IdMonedaOrigen", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdMonedaOrigen);
                this.columnIdMonedaDestino = new DataColumn("IdMonedaDestino", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdMonedaDestino);
                this.columnFechaDeCambioInicio = new DataColumn("FechaDeCambioInicio", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaDeCambioInicio);
                this.columnFechaDeCambioFin = new DataColumn("FechaDeCambioFin", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaDeCambioFin);
                this.columnIdFuenteDeCambio = new DataColumn("IdFuenteDeCambio", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdFuenteDeCambio);
                this.columnValor = new DataColumn("Valor", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnValor);
                this.columnFechaCreacion = new DataColumn("FechaCreacion", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaCreacion);
                this.columnIdConexionCreacion = new DataColumn("IdConexionCreacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionCreacion);
                this.columnUltimaModificacion = new DataColumn("UltimaModificacion", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUltimaModificacion);
                this.columnIdConexionUltimaModificacion = new DataColumn("IdConexionUltimaModificacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionUltimaModificacion);
                this.columnIdReservado = new DataColumn("IdReservado", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdReservado);
                this.columnRowId = new DataColumn("RowId", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowId);
                this.columnIdEmpresa = new DataColumn("IdEmpresa", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdEmpresa);
                this.columnIdSucursal = new DataColumn("IdSucursal", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdSucursal);
                this.Constraints.Add(new UniqueConstraint("tfi_CotizacionesMonedasKey1", new DataColumn[] {
                                this.columnIdCotizacionMoneda}, true));
                this.columnIdCotizacionMoneda.AllowDBNull = false;
                this.columnIdCotizacionMoneda.Unique = true;
                this.columnIdMonedaOrigen.AllowDBNull = false;
                this.columnIdMonedaDestino.AllowDBNull = false;
                this.columnFechaDeCambioInicio.AllowDBNull = false;
                this.columnIdFuenteDeCambio.AllowDBNull = false;
                this.columnUltimaModificacion.ReadOnly = true;
            }
            
            public tfi_CotizacionesMonedasRow Newtfi_CotizacionesMonedasRow() {
                return ((tfi_CotizacionesMonedasRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tfi_CotizacionesMonedasRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tfi_CotizacionesMonedasRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tfi_CotizacionesMonedasRowChanged != null)) {
                    this.tfi_CotizacionesMonedasRowChanged(this, new tfi_CotizacionesMonedasRowChangeEvent(((tfi_CotizacionesMonedasRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tfi_CotizacionesMonedasRowChanging != null)) {
                    this.tfi_CotizacionesMonedasRowChanging(this, new tfi_CotizacionesMonedasRowChangeEvent(((tfi_CotizacionesMonedasRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tfi_CotizacionesMonedasRowDeleted != null)) {
                    this.tfi_CotizacionesMonedasRowDeleted(this, new tfi_CotizacionesMonedasRowChangeEvent(((tfi_CotizacionesMonedasRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tfi_CotizacionesMonedasRowDeleting != null)) {
                    this.tfi_CotizacionesMonedasRowDeleting(this, new tfi_CotizacionesMonedasRowChangeEvent(((tfi_CotizacionesMonedasRow)(e.Row)), e.Action));
                }
            }
            
            public void Removetfi_CotizacionesMonedasRow(tfi_CotizacionesMonedasRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_CotizacionesMonedasRow : DataRow {
            
            private tfi_CotizacionesMonedasDataTable tabletfi_CotizacionesMonedas;
            
            internal tfi_CotizacionesMonedasRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletfi_CotizacionesMonedas = ((tfi_CotizacionesMonedasDataTable)(this.Table));
            }
            
            public string IdCotizacionMoneda {
                get {
                    return ((string)(this[this.tabletfi_CotizacionesMonedas.IdCotizacionMonedaColumn]));
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdCotizacionMonedaColumn] = value;
                }
            }
            
            public string IdMonedaOrigen {
                get {
                    return ((string)(this[this.tabletfi_CotizacionesMonedas.IdMonedaOrigenColumn]));
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdMonedaOrigenColumn] = value;
                }
            }
            
            public string IdMonedaDestino {
                get {
                    return ((string)(this[this.tabletfi_CotizacionesMonedas.IdMonedaDestinoColumn]));
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdMonedaDestinoColumn] = value;
                }
            }
            
            public System.DateTime FechaDeCambioInicio {
                get {
                    return ((System.DateTime)(this[this.tabletfi_CotizacionesMonedas.FechaDeCambioInicioColumn]));
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.FechaDeCambioInicioColumn] = value;
                }
            }
            
            public System.DateTime FechaDeCambioFin {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletfi_CotizacionesMonedas.FechaDeCambioFinColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.FechaDeCambioFinColumn] = value;
                }
            }
            
            public string IdFuenteDeCambio {
                get {
                    return ((string)(this[this.tabletfi_CotizacionesMonedas.IdFuenteDeCambioColumn]));
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdFuenteDeCambioColumn] = value;
                }
            }
            
            public System.Decimal Valor {
                get {
                    try {
                        return ((System.Decimal)(this[this.tabletfi_CotizacionesMonedas.ValorColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.ValorColumn] = value;
                }
            }
            
            public System.DateTime FechaCreacion {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletfi_CotizacionesMonedas.FechaCreacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.FechaCreacionColumn] = value;
                }
            }
            
            public long IdConexionCreacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_CotizacionesMonedas.IdConexionCreacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdConexionCreacionColumn] = value;
                }
            }
            
            public System.Byte[] UltimaModificacion {
                get {
                    try {
                        return ((System.Byte[])(this[this.tabletfi_CotizacionesMonedas.UltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.UltimaModificacionColumn] = value;
                }
            }
            
            public long IdConexionUltimaModificacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_CotizacionesMonedas.IdConexionUltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdConexionUltimaModificacionColumn] = value;
                }
            }
            
            public long IdReservado {
                get {
                    try {
                        return ((long)(this[this.tabletfi_CotizacionesMonedas.IdReservadoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdReservadoColumn] = value;
                }
            }
            
            public System.Guid RowId {
                get {
                    try {
                        return ((System.Guid)(this[this.tabletfi_CotizacionesMonedas.RowIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.RowIdColumn] = value;
                }
            }
            
            public long IdEmpresa {
                get {
                    try {
                        return ((long)(this[this.tabletfi_CotizacionesMonedas.IdEmpresaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdEmpresaColumn] = value;
                }
            }
            
            public long IdSucursal {
                get {
                    try {
                        return ((long)(this[this.tabletfi_CotizacionesMonedas.IdSucursalColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_CotizacionesMonedas.IdSucursalColumn] = value;
                }
            }
            
            public bool IsFechaDeCambioFinNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.FechaDeCambioFinColumn);
            }
            
            public void SetFechaDeCambioFinNull() {
                this[this.tabletfi_CotizacionesMonedas.FechaDeCambioFinColumn] = System.Convert.DBNull;
            }
            
            public bool IsValorNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.ValorColumn);
            }
            
            public void SetValorNull() {
                this[this.tabletfi_CotizacionesMonedas.ValorColumn] = System.Convert.DBNull;
            }
            
            public bool IsFechaCreacionNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.FechaCreacionColumn);
            }
            
            public void SetFechaCreacionNull() {
                this[this.tabletfi_CotizacionesMonedas.FechaCreacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdConexionCreacionNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.IdConexionCreacionColumn);
            }
            
            public void SetIdConexionCreacionNull() {
                this[this.tabletfi_CotizacionesMonedas.IdConexionCreacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.UltimaModificacionColumn);
            }
            
            public void SetUltimaModificacionNull() {
                this[this.tabletfi_CotizacionesMonedas.UltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdConexionUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.IdConexionUltimaModificacionColumn);
            }
            
            public void SetIdConexionUltimaModificacionNull() {
                this[this.tabletfi_CotizacionesMonedas.IdConexionUltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdReservadoNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.IdReservadoColumn);
            }
            
            public void SetIdReservadoNull() {
                this[this.tabletfi_CotizacionesMonedas.IdReservadoColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowIdNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.RowIdColumn);
            }
            
            public void SetRowIdNull() {
                this[this.tabletfi_CotizacionesMonedas.RowIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdEmpresaNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.IdEmpresaColumn);
            }
            
            public void SetIdEmpresaNull() {
                this[this.tabletfi_CotizacionesMonedas.IdEmpresaColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdSucursalNull() {
                return this.IsNull(this.tabletfi_CotizacionesMonedas.IdSucursalColumn);
            }
            
            public void SetIdSucursalNull() {
                this[this.tabletfi_CotizacionesMonedas.IdSucursalColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_CotizacionesMonedasRowChangeEvent : EventArgs {
            
            private tfi_CotizacionesMonedasRow eventRow;
            
            private DataRowAction eventAction;
            
            public tfi_CotizacionesMonedasRowChangeEvent(tfi_CotizacionesMonedasRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tfi_CotizacionesMonedasRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
