//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace mz.erp.commontypes.data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class sy_VariablesPerfilesExDataset : DataSet {
        
        private sy_VariablesPerfilesDataTable tablesy_VariablesPerfiles;
        
        public sy_VariablesPerfilesExDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected sy_VariablesPerfilesExDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["sy_VariablesPerfiles"] != null)) {
                    this.Tables.Add(new sy_VariablesPerfilesDataTable(ds.Tables["sy_VariablesPerfiles"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public sy_VariablesPerfilesDataTable sy_VariablesPerfiles {
            get {
                return this.tablesy_VariablesPerfiles;
            }
        }
        
        public override DataSet Clone() {
            sy_VariablesPerfilesExDataset cln = ((sy_VariablesPerfilesExDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["sy_VariablesPerfiles"] != null)) {
                this.Tables.Add(new sy_VariablesPerfilesDataTable(ds.Tables["sy_VariablesPerfiles"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablesy_VariablesPerfiles = ((sy_VariablesPerfilesDataTable)(this.Tables["sy_VariablesPerfiles"]));
            if ((this.tablesy_VariablesPerfiles != null)) {
                this.tablesy_VariablesPerfiles.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "sy_VariablesPerfilesExDataset";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/sy_VariablesPerfilesEx.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablesy_VariablesPerfiles = new sy_VariablesPerfilesDataTable();
            this.Tables.Add(this.tablesy_VariablesPerfiles);
        }
        
        private bool ShouldSerializesy_VariablesPerfiles() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void sy_VariablesPerfilesRowChangeEventHandler(object sender, sy_VariablesPerfilesRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sy_VariablesPerfilesDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnIdVariable;
            
            private DataColumn columnIdPerfil;
            
            private DataColumn columnValor;
            
            private DataColumn columnFechaCreacion;
            
            private DataColumn columnIdConexionCreacion;
            
            private DataColumn columnUltimaModificacion;
            
            private DataColumn columnIdConexionUltimaModificacion;
            
            private DataColumn columnRowId;
            
            internal sy_VariablesPerfilesDataTable() : 
                    base("sy_VariablesPerfiles") {
                this.InitClass();
            }
            
            internal sy_VariablesPerfilesDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdVariableColumn {
                get {
                    return this.columnIdVariable;
                }
            }
            
            internal DataColumn IdPerfilColumn {
                get {
                    return this.columnIdPerfil;
                }
            }
            
            internal DataColumn ValorColumn {
                get {
                    return this.columnValor;
                }
            }
            
            internal DataColumn FechaCreacionColumn {
                get {
                    return this.columnFechaCreacion;
                }
            }
            
            internal DataColumn IdConexionCreacionColumn {
                get {
                    return this.columnIdConexionCreacion;
                }
            }
            
            internal DataColumn UltimaModificacionColumn {
                get {
                    return this.columnUltimaModificacion;
                }
            }
            
            internal DataColumn IdConexionUltimaModificacionColumn {
                get {
                    return this.columnIdConexionUltimaModificacion;
                }
            }
            
            internal DataColumn RowIdColumn {
                get {
                    return this.columnRowId;
                }
            }
            
            public sy_VariablesPerfilesRow this[int index] {
                get {
                    return ((sy_VariablesPerfilesRow)(this.Rows[index]));
                }
            }
            
            public event sy_VariablesPerfilesRowChangeEventHandler sy_VariablesPerfilesRowChanged;
            
            public event sy_VariablesPerfilesRowChangeEventHandler sy_VariablesPerfilesRowChanging;
            
            public event sy_VariablesPerfilesRowChangeEventHandler sy_VariablesPerfilesRowDeleted;
            
            public event sy_VariablesPerfilesRowChangeEventHandler sy_VariablesPerfilesRowDeleting;
            
            public void Addsy_VariablesPerfilesRow(sy_VariablesPerfilesRow row) {
                this.Rows.Add(row);
            }
            
            public sy_VariablesPerfilesRow Addsy_VariablesPerfilesRow(string IdVariable, long IdPerfil, string Valor, System.DateTime FechaCreacion, long IdConexionCreacion, System.Byte[] UltimaModificacion, long IdConexionUltimaModificacion, System.Guid RowId) {
                sy_VariablesPerfilesRow rowsy_VariablesPerfilesRow = ((sy_VariablesPerfilesRow)(this.NewRow()));
                rowsy_VariablesPerfilesRow.ItemArray = new object[] {
                        IdVariable,
                        IdPerfil,
                        Valor,
                        FechaCreacion,
                        IdConexionCreacion,
                        UltimaModificacion,
                        IdConexionUltimaModificacion,
                        RowId};
                this.Rows.Add(rowsy_VariablesPerfilesRow);
                return rowsy_VariablesPerfilesRow;
            }
            
            public sy_VariablesPerfilesRow FindByIdVariableIdPerfil(string IdVariable, long IdPerfil) {
                return ((sy_VariablesPerfilesRow)(this.Rows.Find(new object[] {
                            IdVariable,
                            IdPerfil})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                sy_VariablesPerfilesDataTable cln = ((sy_VariablesPerfilesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new sy_VariablesPerfilesDataTable();
            }
            
            internal void InitVars() {
                this.columnIdVariable = this.Columns["IdVariable"];
                this.columnIdPerfil = this.Columns["IdPerfil"];
                this.columnValor = this.Columns["Valor"];
                this.columnFechaCreacion = this.Columns["FechaCreacion"];
                this.columnIdConexionCreacion = this.Columns["IdConexionCreacion"];
                this.columnUltimaModificacion = this.Columns["UltimaModificacion"];
                this.columnIdConexionUltimaModificacion = this.Columns["IdConexionUltimaModificacion"];
                this.columnRowId = this.Columns["RowId"];
            }
            
            private void InitClass() {
                this.columnIdVariable = new DataColumn("IdVariable", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdVariable);
                this.columnIdPerfil = new DataColumn("IdPerfil", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdPerfil);
                this.columnValor = new DataColumn("Valor", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnValor);
                this.columnFechaCreacion = new DataColumn("FechaCreacion", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaCreacion);
                this.columnIdConexionCreacion = new DataColumn("IdConexionCreacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionCreacion);
                this.columnUltimaModificacion = new DataColumn("UltimaModificacion", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUltimaModificacion);
                this.columnIdConexionUltimaModificacion = new DataColumn("IdConexionUltimaModificacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionUltimaModificacion);
                this.columnRowId = new DataColumn("RowId", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowId);
                this.Constraints.Add(new UniqueConstraint("sy_VariablesPerfilesExDatasetKey1", new DataColumn[] {
                                this.columnIdVariable,
                                this.columnIdPerfil}, true));
                this.columnIdVariable.AllowDBNull = false;
                this.columnIdPerfil.AllowDBNull = false;
                this.columnValor.AllowDBNull = false;
                this.columnFechaCreacion.AllowDBNull = false;
                this.columnIdConexionCreacion.AllowDBNull = false;
                this.columnUltimaModificacion.ReadOnly = true;
            }
            
            public sy_VariablesPerfilesRow Newsy_VariablesPerfilesRow() {
                return ((sy_VariablesPerfilesRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new sy_VariablesPerfilesRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(sy_VariablesPerfilesRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.sy_VariablesPerfilesRowChanged != null)) {
                    this.sy_VariablesPerfilesRowChanged(this, new sy_VariablesPerfilesRowChangeEvent(((sy_VariablesPerfilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.sy_VariablesPerfilesRowChanging != null)) {
                    this.sy_VariablesPerfilesRowChanging(this, new sy_VariablesPerfilesRowChangeEvent(((sy_VariablesPerfilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.sy_VariablesPerfilesRowDeleted != null)) {
                    this.sy_VariablesPerfilesRowDeleted(this, new sy_VariablesPerfilesRowChangeEvent(((sy_VariablesPerfilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.sy_VariablesPerfilesRowDeleting != null)) {
                    this.sy_VariablesPerfilesRowDeleting(this, new sy_VariablesPerfilesRowChangeEvent(((sy_VariablesPerfilesRow)(e.Row)), e.Action));
                }
            }
            
            public void Removesy_VariablesPerfilesRow(sy_VariablesPerfilesRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sy_VariablesPerfilesRow : DataRow {
            
            private sy_VariablesPerfilesDataTable tablesy_VariablesPerfiles;
            
            internal sy_VariablesPerfilesRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablesy_VariablesPerfiles = ((sy_VariablesPerfilesDataTable)(this.Table));
            }
            
            public string IdVariable {
                get {
                    return ((string)(this[this.tablesy_VariablesPerfiles.IdVariableColumn]));
                }
                set {
                    this[this.tablesy_VariablesPerfiles.IdVariableColumn] = value;
                }
            }
            
            public long IdPerfil {
                get {
                    return ((long)(this[this.tablesy_VariablesPerfiles.IdPerfilColumn]));
                }
                set {
                    this[this.tablesy_VariablesPerfiles.IdPerfilColumn] = value;
                }
            }
            
            public string Valor {
                get {
                    return ((string)(this[this.tablesy_VariablesPerfiles.ValorColumn]));
                }
                set {
                    this[this.tablesy_VariablesPerfiles.ValorColumn] = value;
                }
            }
            
            public System.DateTime FechaCreacion {
                get {
                    return ((System.DateTime)(this[this.tablesy_VariablesPerfiles.FechaCreacionColumn]));
                }
                set {
                    this[this.tablesy_VariablesPerfiles.FechaCreacionColumn] = value;
                }
            }
            
            public long IdConexionCreacion {
                get {
                    return ((long)(this[this.tablesy_VariablesPerfiles.IdConexionCreacionColumn]));
                }
                set {
                    this[this.tablesy_VariablesPerfiles.IdConexionCreacionColumn] = value;
                }
            }
            
            public System.Byte[] UltimaModificacion {
                get {
                    try {
                        return ((System.Byte[])(this[this.tablesy_VariablesPerfiles.UltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tablesy_VariablesPerfiles.UltimaModificacionColumn] = value;
                }
            }
            
            public long IdConexionUltimaModificacion {
                get {
                    try {
                        return ((long)(this[this.tablesy_VariablesPerfiles.IdConexionUltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tablesy_VariablesPerfiles.IdConexionUltimaModificacionColumn] = value;
                }
            }
            
            public System.Guid RowId {
                get {
                    try {
                        return ((System.Guid)(this[this.tablesy_VariablesPerfiles.RowIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tablesy_VariablesPerfiles.RowIdColumn] = value;
                }
            }
            
            public bool IsUltimaModificacionNull() {
                return this.IsNull(this.tablesy_VariablesPerfiles.UltimaModificacionColumn);
            }
            
            public void SetUltimaModificacionNull() {
                this[this.tablesy_VariablesPerfiles.UltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdConexionUltimaModificacionNull() {
                return this.IsNull(this.tablesy_VariablesPerfiles.IdConexionUltimaModificacionColumn);
            }
            
            public void SetIdConexionUltimaModificacionNull() {
                this[this.tablesy_VariablesPerfiles.IdConexionUltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowIdNull() {
                return this.IsNull(this.tablesy_VariablesPerfiles.RowIdColumn);
            }
            
            public void SetRowIdNull() {
                this[this.tablesy_VariablesPerfiles.RowIdColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sy_VariablesPerfilesRowChangeEvent : EventArgs {
            
            private sy_VariablesPerfilesRow eventRow;
            
            private DataRowAction eventAction;
            
            public sy_VariablesPerfilesRowChangeEvent(sy_VariablesPerfilesRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public sy_VariablesPerfilesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
