//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace mz.erp.commontypes.data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("tfi_JerarquiaAgrupTDCompTesoreriaDataset")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class tfi_JerarquiaAgrupTDCompTesoreriaDataset : global::System.Data.DataSet {
        
        private tfi_JerarquiaAgrupTDCompTesoreriaDataTable tabletfi_JerarquiaAgrupTDCompTesoreria;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public tfi_JerarquiaAgrupTDCompTesoreriaDataset() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected tfi_JerarquiaAgrupTDCompTesoreriaDataset(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tfi_JerarquiaAgrupTDCompTesoreria"] != null)) {
                    base.Tables.Add(new tfi_JerarquiaAgrupTDCompTesoreriaDataTable(ds.Tables["tfi_JerarquiaAgrupTDCompTesoreria"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tfi_JerarquiaAgrupTDCompTesoreriaDataTable tfi_JerarquiaAgrupTDCompTesoreria {
            get {
                return this.tabletfi_JerarquiaAgrupTDCompTesoreria;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            tfi_JerarquiaAgrupTDCompTesoreriaDataset cln = ((tfi_JerarquiaAgrupTDCompTesoreriaDataset)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tfi_JerarquiaAgrupTDCompTesoreria"] != null)) {
                    base.Tables.Add(new tfi_JerarquiaAgrupTDCompTesoreriaDataTable(ds.Tables["tfi_JerarquiaAgrupTDCompTesoreria"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabletfi_JerarquiaAgrupTDCompTesoreria = ((tfi_JerarquiaAgrupTDCompTesoreriaDataTable)(base.Tables["tfi_JerarquiaAgrupTDCompTesoreria"]));
            if ((initTable == true)) {
                if ((this.tabletfi_JerarquiaAgrupTDCompTesoreria != null)) {
                    this.tabletfi_JerarquiaAgrupTDCompTesoreria.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "tfi_JerarquiaAgrupTDCompTesoreriaDataset";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/tfi_JerarquiaAgrupTDCompTesoreria.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletfi_JerarquiaAgrupTDCompTesoreria = new tfi_JerarquiaAgrupTDCompTesoreriaDataTable();
            base.Tables.Add(this.tabletfi_JerarquiaAgrupTDCompTesoreria);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializetfi_JerarquiaAgrupTDCompTesoreria() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            tfi_JerarquiaAgrupTDCompTesoreriaDataset ds = new tfi_JerarquiaAgrupTDCompTesoreriaDataset();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEventHandler(object sender, tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tfi_JerarquiaAgrupTDCompTesoreriaDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnIdNomenclatura;
            
            private global::System.Data.DataColumn columnDescripcion;
            
            private global::System.Data.DataColumn columnNivel;
            
            private global::System.Data.DataColumn columnIdPadre;
            
            private global::System.Data.DataColumn columnJerarquia;
            
            private global::System.Data.DataColumn columnAgrupado;
            
            private global::System.Data.DataColumn columnClaveCorta;
            
            private global::System.Data.DataColumn columnClaveLarga;
            
            private global::System.Data.DataColumn columnFechaCreacion;
            
            private global::System.Data.DataColumn columnIdConexionCreacion;
            
            private global::System.Data.DataColumn columnUltimaModificacion;
            
            private global::System.Data.DataColumn columnIdConexionUltimaModificacion;
            
            private global::System.Data.DataColumn columnIdReservado;
            
            private global::System.Data.DataColumn columnRowId;
            
            private global::System.Data.DataColumn columnIdEmpresa;
            
            private global::System.Data.DataColumn columnIdSucursal;
            
            private global::System.Data.DataColumn columnOldIdNomenclatura;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaDataTable() {
                this.TableName = "tfi_JerarquiaAgrupTDCompTesoreria";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal tfi_JerarquiaAgrupTDCompTesoreriaDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected tfi_JerarquiaAgrupTDCompTesoreriaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdNomenclaturaColumn {
                get {
                    return this.columnIdNomenclatura;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DescripcionColumn {
                get {
                    return this.columnDescripcion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NivelColumn {
                get {
                    return this.columnNivel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdPadreColumn {
                get {
                    return this.columnIdPadre;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JerarquiaColumn {
                get {
                    return this.columnJerarquia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AgrupadoColumn {
                get {
                    return this.columnAgrupado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ClaveCortaColumn {
                get {
                    return this.columnClaveCorta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ClaveLargaColumn {
                get {
                    return this.columnClaveLarga;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FechaCreacionColumn {
                get {
                    return this.columnFechaCreacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdConexionCreacionColumn {
                get {
                    return this.columnIdConexionCreacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn UltimaModificacionColumn {
                get {
                    return this.columnUltimaModificacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdConexionUltimaModificacionColumn {
                get {
                    return this.columnIdConexionUltimaModificacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdReservadoColumn {
                get {
                    return this.columnIdReservado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RowIdColumn {
                get {
                    return this.columnRowId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdEmpresaColumn {
                get {
                    return this.columnIdEmpresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IdSucursalColumn {
                get {
                    return this.columnIdSucursal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OldIdNomenclaturaColumn {
                get {
                    return this.columnOldIdNomenclatura;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRow this[int index] {
                get {
                    return ((tfi_JerarquiaAgrupTDCompTesoreriaRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEventHandler tfi_JerarquiaAgrupTDCompTesoreriaRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEventHandler tfi_JerarquiaAgrupTDCompTesoreriaRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEventHandler tfi_JerarquiaAgrupTDCompTesoreriaRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEventHandler tfi_JerarquiaAgrupTDCompTesoreriaRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Addtfi_JerarquiaAgrupTDCompTesoreriaRow(tfi_JerarquiaAgrupTDCompTesoreriaRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRow Addtfi_JerarquiaAgrupTDCompTesoreriaRow(
                        string IdNomenclatura, 
                        string Descripcion, 
                        long Nivel, 
                        string IdPadre, 
                        string Jerarquia, 
                        bool Agrupado, 
                        string ClaveCorta, 
                        string ClaveLarga, 
                        System.DateTime FechaCreacion, 
                        long IdConexionCreacion, 
                        byte[] UltimaModificacion, 
                        long IdConexionUltimaModificacion, 
                        long IdReservado, 
                        System.Guid RowId, 
                        long IdEmpresa, 
                        long IdSucursal, 
                        string OldIdNomenclatura) {
                tfi_JerarquiaAgrupTDCompTesoreriaRow rowtfi_JerarquiaAgrupTDCompTesoreriaRow = ((tfi_JerarquiaAgrupTDCompTesoreriaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IdNomenclatura,
                        Descripcion,
                        Nivel,
                        IdPadre,
                        Jerarquia,
                        Agrupado,
                        ClaveCorta,
                        ClaveLarga,
                        FechaCreacion,
                        IdConexionCreacion,
                        UltimaModificacion,
                        IdConexionUltimaModificacion,
                        IdReservado,
                        RowId,
                        IdEmpresa,
                        IdSucursal,
                        OldIdNomenclatura};
                rowtfi_JerarquiaAgrupTDCompTesoreriaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtfi_JerarquiaAgrupTDCompTesoreriaRow);
                return rowtfi_JerarquiaAgrupTDCompTesoreriaRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRow FindByIdNomenclatura(string IdNomenclatura) {
                return ((tfi_JerarquiaAgrupTDCompTesoreriaRow)(this.Rows.Find(new object[] {
                            IdNomenclatura})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                tfi_JerarquiaAgrupTDCompTesoreriaDataTable cln = ((tfi_JerarquiaAgrupTDCompTesoreriaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tfi_JerarquiaAgrupTDCompTesoreriaDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnIdNomenclatura = base.Columns["IdNomenclatura"];
                this.columnDescripcion = base.Columns["Descripcion"];
                this.columnNivel = base.Columns["Nivel"];
                this.columnIdPadre = base.Columns["IdPadre"];
                this.columnJerarquia = base.Columns["Jerarquia"];
                this.columnAgrupado = base.Columns["Agrupado"];
                this.columnClaveCorta = base.Columns["ClaveCorta"];
                this.columnClaveLarga = base.Columns["ClaveLarga"];
                this.columnFechaCreacion = base.Columns["FechaCreacion"];
                this.columnIdConexionCreacion = base.Columns["IdConexionCreacion"];
                this.columnUltimaModificacion = base.Columns["UltimaModificacion"];
                this.columnIdConexionUltimaModificacion = base.Columns["IdConexionUltimaModificacion"];
                this.columnIdReservado = base.Columns["IdReservado"];
                this.columnRowId = base.Columns["RowId"];
                this.columnIdEmpresa = base.Columns["IdEmpresa"];
                this.columnIdSucursal = base.Columns["IdSucursal"];
                this.columnOldIdNomenclatura = base.Columns["OldIdNomenclatura"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnIdNomenclatura = new global::System.Data.DataColumn("IdNomenclatura", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdNomenclatura);
                this.columnDescripcion = new global::System.Data.DataColumn("Descripcion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcion);
                this.columnNivel = new global::System.Data.DataColumn("Nivel", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNivel);
                this.columnIdPadre = new global::System.Data.DataColumn("IdPadre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdPadre);
                this.columnJerarquia = new global::System.Data.DataColumn("Jerarquia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJerarquia);
                this.columnAgrupado = new global::System.Data.DataColumn("Agrupado", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAgrupado);
                this.columnClaveCorta = new global::System.Data.DataColumn("ClaveCorta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnClaveCorta);
                this.columnClaveLarga = new global::System.Data.DataColumn("ClaveLarga", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnClaveLarga);
                this.columnFechaCreacion = new global::System.Data.DataColumn("FechaCreacion", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFechaCreacion);
                this.columnIdConexionCreacion = new global::System.Data.DataColumn("IdConexionCreacion", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdConexionCreacion);
                this.columnUltimaModificacion = new global::System.Data.DataColumn("UltimaModificacion", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUltimaModificacion);
                this.columnIdConexionUltimaModificacion = new global::System.Data.DataColumn("IdConexionUltimaModificacion", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdConexionUltimaModificacion);
                this.columnIdReservado = new global::System.Data.DataColumn("IdReservado", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdReservado);
                this.columnRowId = new global::System.Data.DataColumn("RowId", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRowId);
                this.columnIdEmpresa = new global::System.Data.DataColumn("IdEmpresa", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdEmpresa);
                this.columnIdSucursal = new global::System.Data.DataColumn("IdSucursal", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdSucursal);
                this.columnOldIdNomenclatura = new global::System.Data.DataColumn("OldIdNomenclatura", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOldIdNomenclatura);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("tfi_JerarquiaAgrupTDCompTesoreriaKey1", new global::System.Data.DataColumn[] {
                                this.columnIdNomenclatura}, true));
                this.columnIdNomenclatura.AllowDBNull = false;
                this.columnIdNomenclatura.Unique = true;
                this.columnJerarquia.AllowDBNull = false;
                this.columnClaveCorta.AllowDBNull = false;
                this.columnClaveLarga.AllowDBNull = false;
                this.columnUltimaModificacion.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRow Newtfi_JerarquiaAgrupTDCompTesoreriaRow() {
                return ((tfi_JerarquiaAgrupTDCompTesoreriaRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tfi_JerarquiaAgrupTDCompTesoreriaRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(tfi_JerarquiaAgrupTDCompTesoreriaRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tfi_JerarquiaAgrupTDCompTesoreriaRowChanged != null)) {
                    this.tfi_JerarquiaAgrupTDCompTesoreriaRowChanged(this, new tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent(((tfi_JerarquiaAgrupTDCompTesoreriaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tfi_JerarquiaAgrupTDCompTesoreriaRowChanging != null)) {
                    this.tfi_JerarquiaAgrupTDCompTesoreriaRowChanging(this, new tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent(((tfi_JerarquiaAgrupTDCompTesoreriaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tfi_JerarquiaAgrupTDCompTesoreriaRowDeleted != null)) {
                    this.tfi_JerarquiaAgrupTDCompTesoreriaRowDeleted(this, new tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent(((tfi_JerarquiaAgrupTDCompTesoreriaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tfi_JerarquiaAgrupTDCompTesoreriaRowDeleting != null)) {
                    this.tfi_JerarquiaAgrupTDCompTesoreriaRowDeleting(this, new tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent(((tfi_JerarquiaAgrupTDCompTesoreriaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Removetfi_JerarquiaAgrupTDCompTesoreriaRow(tfi_JerarquiaAgrupTDCompTesoreriaRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                tfi_JerarquiaAgrupTDCompTesoreriaDataset ds = new tfi_JerarquiaAgrupTDCompTesoreriaDataset();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tfi_JerarquiaAgrupTDCompTesoreriaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class tfi_JerarquiaAgrupTDCompTesoreriaRow : global::System.Data.DataRow {
            
            private tfi_JerarquiaAgrupTDCompTesoreriaDataTable tabletfi_JerarquiaAgrupTDCompTesoreria;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal tfi_JerarquiaAgrupTDCompTesoreriaRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletfi_JerarquiaAgrupTDCompTesoreria = ((tfi_JerarquiaAgrupTDCompTesoreriaDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IdNomenclatura {
                get {
                    return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdNomenclaturaColumn]));
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdNomenclaturaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Descripcion {
                get {
                    try {
                        return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.DescripcionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Descripcion\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.DescripcionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long Nivel {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.NivelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Nivel\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.NivelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IdPadre {
                get {
                    try {
                        return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdPadreColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdPadre\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdPadreColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Jerarquia {
                get {
                    return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.JerarquiaColumn]));
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.JerarquiaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Agrupado {
                get {
                    try {
                        return ((bool)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.AgrupadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Agrupado\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.AgrupadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ClaveCorta {
                get {
                    return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.ClaveCortaColumn]));
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.ClaveCortaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ClaveLarga {
                get {
                    return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.ClaveLargaColumn]));
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.ClaveLargaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime FechaCreacion {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.FechaCreacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FechaCreacion\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.FechaCreacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long IdConexionCreacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionCreacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdConexionCreacion\' in table \'tfi_JerarquiaAgrupTDCompTesor" +
                                "eria\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionCreacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] UltimaModificacion {
                get {
                    try {
                        return ((byte[])(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.UltimaModificacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UltimaModificacion\' in table \'tfi_JerarquiaAgrupTDCompTesor" +
                                "eria\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.UltimaModificacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long IdConexionUltimaModificacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionUltimaModificacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdConexionUltimaModificacion\' in table \'tfi_JerarquiaAgrupT" +
                                "DCompTesoreria\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionUltimaModificacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long IdReservado {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdReservadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdReservado\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdReservadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.Guid RowId {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.RowIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RowId\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.RowIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long IdEmpresa {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdEmpresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdEmpresa\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdEmpresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long IdSucursal {
                get {
                    try {
                        return ((long)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdSucursalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdSucursal\' in table \'tfi_JerarquiaAgrupTDCompTesoreria\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdSucursalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OldIdNomenclatura {
                get {
                    try {
                        return ((string)(this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.OldIdNomenclaturaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OldIdNomenclatura\' in table \'tfi_JerarquiaAgrupTDCompTesore" +
                                "ria\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.OldIdNomenclaturaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDescripcionNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.DescripcionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDescripcionNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.DescripcionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNivelNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.NivelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNivelNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.NivelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdPadreNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdPadreColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdPadreNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdPadreColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAgrupadoNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.AgrupadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAgrupadoNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.AgrupadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFechaCreacionNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.FechaCreacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFechaCreacionNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.FechaCreacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdConexionCreacionNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionCreacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdConexionCreacionNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionCreacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.UltimaModificacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUltimaModificacionNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.UltimaModificacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdConexionUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionUltimaModificacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdConexionUltimaModificacionNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdConexionUltimaModificacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdReservadoNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdReservadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdReservadoNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdReservadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRowIdNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.RowIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRowIdNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.RowIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdEmpresaNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdEmpresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdEmpresaNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdEmpresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIdSucursalNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdSucursalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIdSucursalNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.IdSucursalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOldIdNomenclaturaNull() {
                return this.IsNull(this.tabletfi_JerarquiaAgrupTDCompTesoreria.OldIdNomenclaturaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOldIdNomenclaturaNull() {
                this[this.tabletfi_JerarquiaAgrupTDCompTesoreria.OldIdNomenclaturaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent : global::System.EventArgs {
            
            private tfi_JerarquiaAgrupTDCompTesoreriaRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRowChangeEvent(tfi_JerarquiaAgrupTDCompTesoreriaRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public tfi_JerarquiaAgrupTDCompTesoreriaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591