//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace mz.erp.commontypes.data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class tfi_TDCompTesoreriasMonedasRecargosDataset : DataSet {
        
        private tfi_TDCompTesoreriasMonedasRecargosDataTable tabletfi_TDCompTesoreriasMonedasRecargos;
        
        public tfi_TDCompTesoreriasMonedasRecargosDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected tfi_TDCompTesoreriasMonedasRecargosDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tfi_TDCompTesoreriasMonedasRecargos"] != null)) {
                    this.Tables.Add(new tfi_TDCompTesoreriasMonedasRecargosDataTable(ds.Tables["tfi_TDCompTesoreriasMonedasRecargos"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tfi_TDCompTesoreriasMonedasRecargosDataTable tfi_TDCompTesoreriasMonedasRecargos {
            get {
                return this.tabletfi_TDCompTesoreriasMonedasRecargos;
            }
        }
        
        public override DataSet Clone() {
            tfi_TDCompTesoreriasMonedasRecargosDataset cln = ((tfi_TDCompTesoreriasMonedasRecargosDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tfi_TDCompTesoreriasMonedasRecargos"] != null)) {
                this.Tables.Add(new tfi_TDCompTesoreriasMonedasRecargosDataTable(ds.Tables["tfi_TDCompTesoreriasMonedasRecargos"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletfi_TDCompTesoreriasMonedasRecargos = ((tfi_TDCompTesoreriasMonedasRecargosDataTable)(this.Tables["tfi_TDCompTesoreriasMonedasRecargos"]));
            if ((this.tabletfi_TDCompTesoreriasMonedasRecargos != null)) {
                this.tabletfi_TDCompTesoreriasMonedasRecargos.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "tfi_TDCompTesoreriasMonedasRecargosDataset";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/tfi_TDCompTesoreriasMonedasRecargos.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletfi_TDCompTesoreriasMonedasRecargos = new tfi_TDCompTesoreriasMonedasRecargosDataTable();
            this.Tables.Add(this.tabletfi_TDCompTesoreriasMonedasRecargos);
        }
        
        private bool ShouldSerializetfi_TDCompTesoreriasMonedasRecargos() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tfi_TDCompTesoreriasMonedasRecargosRowChangeEventHandler(object sender, tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_TDCompTesoreriasMonedasRecargosDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnIdTDCompTesoreria;
            
            private DataColumn columnIdMoneda;
            
            private DataColumn columnRecargo;
            
            private DataColumn columnFechaCreacion;
            
            private DataColumn columnIdConexionCreacion;
            
            private DataColumn columnUltimaModificacion;
            
            private DataColumn columnIdConexionUltimaModificacion;
            
            private DataColumn columnIdReservado;
            
            private DataColumn columnRowId;
            
            private DataColumn columnIdEmpresa;
            
            private DataColumn columnIdSucursal;
            
            private DataColumn columnIdFormaDePago;
            
            internal tfi_TDCompTesoreriasMonedasRecargosDataTable() : 
                    base("tfi_TDCompTesoreriasMonedasRecargos") {
                this.InitClass();
            }
            
            internal tfi_TDCompTesoreriasMonedasRecargosDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdTDCompTesoreriaColumn {
                get {
                    return this.columnIdTDCompTesoreria;
                }
            }
            
            internal DataColumn IdMonedaColumn {
                get {
                    return this.columnIdMoneda;
                }
            }
            
            internal DataColumn RecargoColumn {
                get {
                    return this.columnRecargo;
                }
            }
            
            internal DataColumn FechaCreacionColumn {
                get {
                    return this.columnFechaCreacion;
                }
            }
            
            internal DataColumn IdConexionCreacionColumn {
                get {
                    return this.columnIdConexionCreacion;
                }
            }
            
            internal DataColumn UltimaModificacionColumn {
                get {
                    return this.columnUltimaModificacion;
                }
            }
            
            internal DataColumn IdConexionUltimaModificacionColumn {
                get {
                    return this.columnIdConexionUltimaModificacion;
                }
            }
            
            internal DataColumn IdReservadoColumn {
                get {
                    return this.columnIdReservado;
                }
            }
            
            internal DataColumn RowIdColumn {
                get {
                    return this.columnRowId;
                }
            }
            
            internal DataColumn IdEmpresaColumn {
                get {
                    return this.columnIdEmpresa;
                }
            }
            
            internal DataColumn IdSucursalColumn {
                get {
                    return this.columnIdSucursal;
                }
            }
            
            internal DataColumn IdFormaDePagoColumn {
                get {
                    return this.columnIdFormaDePago;
                }
            }
            
            public tfi_TDCompTesoreriasMonedasRecargosRow this[int index] {
                get {
                    return ((tfi_TDCompTesoreriasMonedasRecargosRow)(this.Rows[index]));
                }
            }
            
            public event tfi_TDCompTesoreriasMonedasRecargosRowChangeEventHandler tfi_TDCompTesoreriasMonedasRecargosRowChanged;
            
            public event tfi_TDCompTesoreriasMonedasRecargosRowChangeEventHandler tfi_TDCompTesoreriasMonedasRecargosRowChanging;
            
            public event tfi_TDCompTesoreriasMonedasRecargosRowChangeEventHandler tfi_TDCompTesoreriasMonedasRecargosRowDeleted;
            
            public event tfi_TDCompTesoreriasMonedasRecargosRowChangeEventHandler tfi_TDCompTesoreriasMonedasRecargosRowDeleting;
            
            public void Addtfi_TDCompTesoreriasMonedasRecargosRow(tfi_TDCompTesoreriasMonedasRecargosRow row) {
                this.Rows.Add(row);
            }
            
            public tfi_TDCompTesoreriasMonedasRecargosRow Addtfi_TDCompTesoreriasMonedasRecargosRow(string IdTDCompTesoreria, string IdMoneda, System.Decimal Recargo, System.DateTime FechaCreacion, long IdConexionCreacion, System.Byte[] UltimaModificacion, long IdConexionUltimaModificacion, long IdReservado, System.Guid RowId, long IdEmpresa, long IdSucursal, string IdFormaDePago) {
                tfi_TDCompTesoreriasMonedasRecargosRow rowtfi_TDCompTesoreriasMonedasRecargosRow = ((tfi_TDCompTesoreriasMonedasRecargosRow)(this.NewRow()));
                rowtfi_TDCompTesoreriasMonedasRecargosRow.ItemArray = new object[] {
                        IdTDCompTesoreria,
                        IdMoneda,
                        Recargo,
                        FechaCreacion,
                        IdConexionCreacion,
                        UltimaModificacion,
                        IdConexionUltimaModificacion,
                        IdReservado,
                        RowId,
                        IdEmpresa,
                        IdSucursal,
                        IdFormaDePago};
                this.Rows.Add(rowtfi_TDCompTesoreriasMonedasRecargosRow);
                return rowtfi_TDCompTesoreriasMonedasRecargosRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tfi_TDCompTesoreriasMonedasRecargosDataTable cln = ((tfi_TDCompTesoreriasMonedasRecargosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tfi_TDCompTesoreriasMonedasRecargosDataTable();
            }
            
            internal void InitVars() {
                this.columnIdTDCompTesoreria = this.Columns["IdTDCompTesoreria"];
                this.columnIdMoneda = this.Columns["IdMoneda"];
                this.columnRecargo = this.Columns["Recargo"];
                this.columnFechaCreacion = this.Columns["FechaCreacion"];
                this.columnIdConexionCreacion = this.Columns["IdConexionCreacion"];
                this.columnUltimaModificacion = this.Columns["UltimaModificacion"];
                this.columnIdConexionUltimaModificacion = this.Columns["IdConexionUltimaModificacion"];
                this.columnIdReservado = this.Columns["IdReservado"];
                this.columnRowId = this.Columns["RowId"];
                this.columnIdEmpresa = this.Columns["IdEmpresa"];
                this.columnIdSucursal = this.Columns["IdSucursal"];
                this.columnIdFormaDePago = this.Columns["IdFormaDePago"];
            }
            
            private void InitClass() {
                this.columnIdTDCompTesoreria = new DataColumn("IdTDCompTesoreria", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdTDCompTesoreria);
                this.columnIdMoneda = new DataColumn("IdMoneda", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdMoneda);
                this.columnRecargo = new DataColumn("Recargo", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRecargo);
                this.columnFechaCreacion = new DataColumn("FechaCreacion", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaCreacion);
                this.columnIdConexionCreacion = new DataColumn("IdConexionCreacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionCreacion);
                this.columnUltimaModificacion = new DataColumn("UltimaModificacion", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUltimaModificacion);
                this.columnIdConexionUltimaModificacion = new DataColumn("IdConexionUltimaModificacion", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdConexionUltimaModificacion);
                this.columnIdReservado = new DataColumn("IdReservado", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdReservado);
                this.columnRowId = new DataColumn("RowId", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowId);
                this.columnIdEmpresa = new DataColumn("IdEmpresa", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdEmpresa);
                this.columnIdSucursal = new DataColumn("IdSucursal", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdSucursal);
                this.columnIdFormaDePago = new DataColumn("IdFormaDePago", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdFormaDePago);
                this.columnIdTDCompTesoreria.AllowDBNull = false;
                this.columnIdMoneda.AllowDBNull = false;
                this.columnRecargo.AllowDBNull = false;
                this.columnUltimaModificacion.ReadOnly = true;
            }
            
            public tfi_TDCompTesoreriasMonedasRecargosRow Newtfi_TDCompTesoreriasMonedasRecargosRow() {
                return ((tfi_TDCompTesoreriasMonedasRecargosRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tfi_TDCompTesoreriasMonedasRecargosRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tfi_TDCompTesoreriasMonedasRecargosRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tfi_TDCompTesoreriasMonedasRecargosRowChanged != null)) {
                    this.tfi_TDCompTesoreriasMonedasRecargosRowChanged(this, new tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent(((tfi_TDCompTesoreriasMonedasRecargosRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tfi_TDCompTesoreriasMonedasRecargosRowChanging != null)) {
                    this.tfi_TDCompTesoreriasMonedasRecargosRowChanging(this, new tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent(((tfi_TDCompTesoreriasMonedasRecargosRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tfi_TDCompTesoreriasMonedasRecargosRowDeleted != null)) {
                    this.tfi_TDCompTesoreriasMonedasRecargosRowDeleted(this, new tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent(((tfi_TDCompTesoreriasMonedasRecargosRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tfi_TDCompTesoreriasMonedasRecargosRowDeleting != null)) {
                    this.tfi_TDCompTesoreriasMonedasRecargosRowDeleting(this, new tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent(((tfi_TDCompTesoreriasMonedasRecargosRow)(e.Row)), e.Action));
                }
            }
            
            public void Removetfi_TDCompTesoreriasMonedasRecargosRow(tfi_TDCompTesoreriasMonedasRecargosRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_TDCompTesoreriasMonedasRecargosRow : DataRow {
            
            private tfi_TDCompTesoreriasMonedasRecargosDataTable tabletfi_TDCompTesoreriasMonedasRecargos;
            
            internal tfi_TDCompTesoreriasMonedasRecargosRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletfi_TDCompTesoreriasMonedasRecargos = ((tfi_TDCompTesoreriasMonedasRecargosDataTable)(this.Table));
            }
            
            public string IdTDCompTesoreria {
                get {
                    return ((string)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdTDCompTesoreriaColumn]));
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdTDCompTesoreriaColumn] = value;
                }
            }
            
            public string IdMoneda {
                get {
                    return ((string)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdMonedaColumn]));
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdMonedaColumn] = value;
                }
            }
            
            public System.Decimal Recargo {
                get {
                    return ((System.Decimal)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.RecargoColumn]));
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.RecargoColumn] = value;
                }
            }
            
            public System.DateTime FechaCreacion {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.FechaCreacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.FechaCreacionColumn] = value;
                }
            }
            
            public long IdConexionCreacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionCreacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionCreacionColumn] = value;
                }
            }
            
            public System.Byte[] UltimaModificacion {
                get {
                    try {
                        return ((System.Byte[])(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.UltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.UltimaModificacionColumn] = value;
                }
            }
            
            public long IdConexionUltimaModificacion {
                get {
                    try {
                        return ((long)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionUltimaModificacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionUltimaModificacionColumn] = value;
                }
            }
            
            public long IdReservado {
                get {
                    try {
                        return ((long)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdReservadoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdReservadoColumn] = value;
                }
            }
            
            public System.Guid RowId {
                get {
                    try {
                        return ((System.Guid)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.RowIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.RowIdColumn] = value;
                }
            }
            
            public long IdEmpresa {
                get {
                    try {
                        return ((long)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdEmpresaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdEmpresaColumn] = value;
                }
            }
            
            public long IdSucursal {
                get {
                    try {
                        return ((long)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdSucursalColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdSucursalColumn] = value;
                }
            }
            
            public string IdFormaDePago {
                get {
                    try {
                        return ((string)(this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdFormaDePagoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdFormaDePagoColumn] = value;
                }
            }
            
            public bool IsFechaCreacionNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.FechaCreacionColumn);
            }
            
            public void SetFechaCreacionNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.FechaCreacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdConexionCreacionNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionCreacionColumn);
            }
            
            public void SetIdConexionCreacionNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionCreacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.UltimaModificacionColumn);
            }
            
            public void SetUltimaModificacionNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.UltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdConexionUltimaModificacionNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionUltimaModificacionColumn);
            }
            
            public void SetIdConexionUltimaModificacionNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdConexionUltimaModificacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdReservadoNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdReservadoColumn);
            }
            
            public void SetIdReservadoNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdReservadoColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowIdNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.RowIdColumn);
            }
            
            public void SetRowIdNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.RowIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdEmpresaNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdEmpresaColumn);
            }
            
            public void SetIdEmpresaNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdEmpresaColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdSucursalNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdSucursalColumn);
            }
            
            public void SetIdSucursalNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdSucursalColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdFormaDePagoNull() {
                return this.IsNull(this.tabletfi_TDCompTesoreriasMonedasRecargos.IdFormaDePagoColumn);
            }
            
            public void SetIdFormaDePagoNull() {
                this[this.tabletfi_TDCompTesoreriasMonedasRecargos.IdFormaDePagoColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent : EventArgs {
            
            private tfi_TDCompTesoreriasMonedasRecargosRow eventRow;
            
            private DataRowAction eventAction;
            
            public tfi_TDCompTesoreriasMonedasRecargosRowChangeEvent(tfi_TDCompTesoreriasMonedasRecargosRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tfi_TDCompTesoreriasMonedasRecargosRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
